framework:
    cache:
        pools:
            cache.oro_layout.render:
                adapter: cache.adapter.redis_tag_aware
                provider: snc_redis.layout
snc_redis:
    clients:
        layout:
            type: predis
            alias: layout
            options:
                connection_persistent: true
                profile: 3.2
oro_message_queue:
    persistent_services:
        # `snc_redis.layout` can be persistent in order to not duplicate connections on container clear
        - 'snc_redis.layout'
